AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Bundler/OrderedGems:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstHashElementLineBreak:
  Enabled: true # Opt-in

Layout/FirstMethodArgumentLineBreak:
  Enabled: true # Opt-in

Layout/FirstMethodParameterLineBreak:
  Enabled: true # Opt-in

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics:
  Enabled: false

Naming/MethodParameterName:
  Exclude: [spec/**/*.rb]

Lint/EmptyBlock:
  Exclude: [spec/**/*.rb]

Lint/Void:
  Enabled: false

Security/MarshalLoad:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
